language: python

env:
  matrix:
    - TOXENV=py26
    - TOXENV=py27
    - TOXENV=py32
    - TOXENV=py33
    - TOXENV=py34
    - TOXENV=py35

matrix:
  include:
    - python: 3.5
      env: TOXENV=py35

install:
  - pip install tox
  - if [[ "${TOXENV}" == "py32" ]]; then
      pip install "virtualenv<14.0" ;
    fi
script: tox
